<p>The preliminary policy issues report is available at <a href="http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm">http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm</a> Online comments are&nbsp;very welcome and will be discussed&nbsp;during this session. Comments on the report can be posted to <a href="mailto:idn-tlds-comments@icann.org">idn-tlds-comments@icann.org</a> and viewed at <a href="http://forum.icann.org/lists/idn-tlds-comments">http://forum.icann.org/lists/idn-tlds-comments</a>. </p>

<p>The preliminary policy issues report is available at <a href="http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm">http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm</a> Online comments are&nbsp;very welcome and will be discussed&nbsp;during this session. Comments on the report can be posted to <a href="mailto:idn-tlds-comments@icann.org">idn-tlds-comments@icann.org</a> and viewed at <a href="http://forum.icann.org/lists/idn-tlds-comments">http://forum.icann.org/lists/idn-tlds-comments</a>. </p>

<p>The preliminary policy issues report is available at <a href="http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm">http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm</a> Online comments are&nbsp;very welcome and will be discussed&nbsp;during this session. Comments on the report can be posted to <a href="mailto:idn-tlds-comments@icann.org">idn-tlds-comments@icann.org</a> and viewed at <a href="http://forum.icann.org/lists/idn-tlds-comments">http://forum.icann.org/lists/idn-tlds-comments</a>. </p>

<p>The preliminary policy issues report is available at <a href="http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm">http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm</a> Online comments are&nbsp;very welcome and will be discussed&nbsp;during this session. Comments on the report can be posted to <a href="mailto:idn-tlds-comments@icann.org">idn-tlds-comments@icann.org</a> and viewed at <a href="http://forum.icann.org/lists/idn-tlds-comments">http://forum.icann.org/lists/idn-tlds-comments</a>. </p>

<p>The preliminary policy issues report is available at <a href="http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm">http://gnso.icann.org/issues/idn-tlds/issues-report-28may06.htm</a> Online comments are&nbsp;very welcome and will be discussed&nbsp;during this session. Comments on the report can be posted to <a href="mailto:idn-tlds-comments@icann.org">idn-tlds-comments@icann.org</a> and viewed at <a href="http://forum.icann.org/lists/idn-tlds-comments">http://forum.icann.org/lists/idn-tlds-comments</a>. </p>


